import NextNProgress from 'nextjs-progressbar';
import Head from 'next/head';
import '../styles/globals.css';
import type { AppProps } from 'next/app';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Buzzer Finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NextNProgress
        color='#29D'
        stopDelayMs={200}
        height={3}
        options={{ showSpinner: false, easing: 'ease', speed: 500 }}
      />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
